BEGIN;
UPDATE ACCOUNTS SET BALANCE =BALACE+500 WHERE ID=1;
UPDATE ACCOUNTS SET BALANCE =BALACE-500 WHERE ID=2;
COMMIT


alter table acoounts
add constrain BALANCE_POSITIVE
CHECK (BALANCE>=0)


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
